# Dockerfile.good
FROM node:20-alpine

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN chown -R appuser:appgroup /app

USER appuser

CMD ["node", "-e", "console.log('Je suis un utilisateur sécurisé (appuser)'); setInterval(() => {}, 1000);"]